targets:
  $default:
    sources:
      exclude:
        # Exclude files with syntax errors
        - 'lib/config/env_config.dart'
        - 'lib/screens/workout_detail_screen.dart'
        - 'lib/main.dart'
    builders:
      json_serializable:
        options:
          explicit_to_json: true
